<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>NACOSS</title>

   <link href="{{asset('css/app.css')}}" rel="stylesheet">
   <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
   <link href="{{asset('css/vote.css')}}" rel="stylesheet">
 

</head>

<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">NACOSS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">ABOUT <span class="sr-only">(current)</span></a></li>
        <li><a href="#">EVENT</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CONTACT <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">CONTACT</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">SOCIALS HERE</a></li>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<div class="container">
    <div class="row hidden-md hidden-lg">
          <div class="col-xs-12 text-center">
                        <h1>2017/2018</h1>
                        <h2>NACOSS VOTING</h2>
                        <br>
                        <p class="text-justify"> 
                          The election is stickly for naccosite of salem university chapter and is not for the 
                          general public. 
                        </p>

                  </div>
    
    </div>
    <div class="row hold-banner">
            <div class="col-xs-8  hidden-xs hidden-sm text-center">
                  <h1>2017/2018</h1>
                  <h2>NACOSS VOTING</h2>
                  <br>
                  <p class="text-justify"> 
                    The election is stickly for naccosite of salem university chapter and is not for the 
                    general public. the elcetion is to last for just an hour after which results would be autogenerated by the system
                    5 minutes after voting is closed.
                    Users and also the general public should be aware that any form of hacking would metaphone
                    immedate disqalification of that party.
                  </p>

            </div>
            <div class="col-xs-12 col-sm-12  col-md-4 col-lg-4">
                <div class="col-xs-12">

                
               
                @if($a->smode==='0')
                <div style="margin-top:60px;" data-type="countdown" data-id="562268" class="tickcounter" style="width: 100%; position: relative; padding-bottom: 25%"><a href="//www.tickcounter.com/countdown/562268/election-starts" title="ELECTION STARTS">ELECTION STARTS</a><a href="//www.tickcounter.com/" title="Countdown">Countdown</a></div><script>(function(d, s, id) { var js, pjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//www.tickcounter.com/static/js/loader.js"; pjs.parentNode.insertBefore(js, pjs); }(document, "script", "tickcounter-sdk"));</script>
              @endif
              @if($a->smode==='2')
                      <h2>VOTING IS OVER</h2>
                      <hr>
                      <a href="/result">
                      
                      <button class="btn-lg btn-danger">SEE RESULT</button>
                      
                      </a>
                      @endif


                      @if($a->smode==='1')

                      <form action="/" method="post" class="text-center form">
                    {{csrf_field()}}
                                <h3 class="text-center"> Start Voting </h3>
                                <p class="text-center text-capitalize">
                                  To start voting please fill in the form below correctly
                                </p>
<!-- 
                                <div class="form-group">
                                <label for="name">Fullname</label>
                                <input type="text" class="form-control" placeholder="full name required" require=required name="name" id="name">
                                <small id="namehelp" class="form-text text-muted"></small> 
                            </div>
                     -->
                              <div class="form-group">
                                  <label for="passcode">PassCode</label>
                                  <input type="password" class="form-control" placeholder="passcode" require=required name="code" id="passcode">
                                  <small id="passcode" class="form-text text-muted">please provide your passcode</small> 
                              </div>

                    
                            <button type="submit" class="btn btn-primary">Start voting</button> <br>  
                            <small id="passcode" class="form-text text-muted">do not exit the brower until you're completely done voting </small> 
                          
                  
                  </form>


                      @endif
        
                </div>
            </div>
    </div>
</div>

   
    </body>
</html>
